core/urls.py
from django.urls import path, include
from django.contrib import admin
import django.core.handlers.wsgi
from . import views 
from django.conf.urls.static import static
from django.conf import settings
from .forms import LoginForm, SignUpForm, AuthenticationForm, EmailAuthenticationForm
from django.contrib.auth import views as auth_views
from . import api
# from rest_framework_jwt.views import obtain_jwt_token
from rest_framework.authtoken.views import obtain_auth_token
urlpatterns = [
    
 
    path('admin/',admin.site.urls),
    # path('<str:hmac>/<str:locale>/<str:session>/<str:shop>/<str:timestamp>/',include('shop.urls'))
    path('',views.user_login, name='mvp'),
    path('ordermanage/',include('ordermanage.urls')),
    path('signup/',views.signup,name='signup'),
    path('logout/',django.contrib.auth.views.LogoutView.as_view(),name='logout'),
    path('shop/',include('shop.urls')),
    path('shopify_app/',include('shopify_admin.urls')),
    
    path('mf_store/',include('mfStore.urls')),



    #PASSWORD VIEWS - AUTH BASED
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('auth/',include('rest_framework_social_oauth2.urls')),#heroku comment

#####################################react app###############################################    
    path('frontend/',include('frontend.urls')),
#############################################################################################
#############################################################intregting api with #############################    
    path('apitoken/', obtain_auth_token, name='api_token_auth'),
    path('api/',api.auth.as_view()),
    path('api/signup/',api.Signup.as_view()),
    path('api/product_list/',api.Product_list.as_view()),
    path('api/product_list/<str:rate>/',api.get_by_count.as_view()),
    path('api/shopify/',api.getshopify.as_view())
#########################################################################################
    
]


"""for Lodaing Static files in django """

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""End Of  Lodaing Static files in django """

shop/urls.py
from django.urls import path
from . import views 

app_name='shop'

urlpatterns = [
    # url(r'^$', views.product_list, name='product_list'),
    # url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    # url(r'^(?P<id>\d+)/edit/$', views.edit, name="edit"),
    # url(r'^(?P<id>\d+)/delete/$', views.product_delete, name="delete"),
    # #url(r'^/create/$', views.create, name="create"),
    # url(r'^product/create/$', views.create, name="create"),
    # url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    # url(r'^product/company_stock/$', views.company_stock, name='company_stock'),
    # url(r'^product/category/$', views.category, name='category'),
    # url(r'^product/addcompany/$', views.AddCompanySku, name='addcompany'),
    # url(r'^product/company/$', views.AddCompany, name='company'),
    # url(r'^product/hundred/$', views.inventory_hundred_Percent, name='hundred'),
    # url(r'^product/lesthantwenty/$', views.inventory_twenty, name='lesthantwenty'),
    # url(r'^product/inventory_inrange/$', views.inventory_inrange, name='inventory_inrange'),
    # url(r'^product/create_product/$', views.CreateProduct, name='create_product'),
    # url(r'^product/shopifyGetProduct/$', views.shopifyGetProduct, name='shopifyGetProduct')
    # url(r'^company_stock/$', views.company_stock, name='company_stock'), 

    path('',views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,name='product_list_by_category'),
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id/delete/', views.product_delete, name='delete'),
    # path('create/',views.create, name='create')
    path('product/create/', views.create, name='create'),
    path('<int:id>/<slug:slug>/',views.product_detail, name='product_detail'),
    path('product/company_stock/',views.company_stock,name='company_stock'),
    path('product/category/',views.category, name='category'),
    path('product/addcompany/', views.AddCompanySku, name='addcompany'),
    path('product/company/',views.AddCompany, name='company'),
    path('product/hundred/', views.inventory_hundred_Percent, name='hundred'),
    path('product/lesthantwenty/', views.inventory_twenty, name='lesthantwenty'),
    path('product/inventory_inrange/', views.inventory_inrange, name='inventory_inrange'),
    path('product/create_product/', views.CreateProduct, name='create_product'),
    path('product/shopifyGetProduct/', views.shopifyGetProduct, name='shopifyGetProduct')
    # path('company_stock/',views.company_stock, name='company_stock')

]

shop/models.py
from django.db import models
from django.urls import reverse
from django.core.signals import request_finished
from django.db.models.signals import pre_save
from django.dispatch import receiver
# from ordermanage.models import Company1


#
class Category(models.Model): 
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])
########################################################################################



class Products(models.Model):
    product_id = models.PositiveIntegerField(unique=True)#product id
    title = models.CharField(max_length=200)#name of product
    product_image = models.FileField(upload_to='products/%Y/%m/%d', blank=True)
    body_html = models.TextField()#contents of prodct
    vendor = models.CharField(max_length=200)#vendor name
    product_type = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    handel = models.CharField(max_length=100)#name

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.product_id])

class Variant(models.Model):
    product_id = models.ForeignKey(Products,on_delete=models.CASCADE)
    variant_id = models.PositiveIntegerField(unique=True)
    title = models.CharField(max_length=200)#name of varient
    variant_image = models.FileField(upload_to='products/%Y/%m/%d', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    variant_sku = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200, db_index=True)
    compare_at_price = models.DecimalField(max_digits=10, decimal_places=2)
    inventory_item_id = models.PositiveIntegerField()
    inventory_item_quantity = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    grams = models.CharField(max_length=20)
    weight =  models.IntegerField(default=0)
    weight_unit = models.CharField(max_length=20)
    inventory_policy =  models.CharField(max_length=20)

    def __str__(self):
        return self.product_id.title+":"+self.title
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.variant_id,self.slug])
# ############################################################################################### 
# class Product(models.Model):#inventry table  
    
#     # Product_id = models.PositiveIntegerField(default=None, blank=True, null=True ) #remove True
#     Product_SKU = models.CharField(max_length=20, unique=True)
#     name = models.CharField(max_length=200, db_index=True) # name of the product
#     slug = models.SlugField(max_length=200, db_index=True,) # built beautiful url 
#     image = models.FileField(upload_to='products/%Y/%m/%d', blank=True)
#     description = models.TextField(blank=True)
#     bulletpoints = models.TextField(blank=True)
#     category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
#     Product_Dimensions = models.CharField(max_length=20, blank = False ,null = False)
#     Color = models.CharField(blank = False ,null = False, max_length=20)
#     price = models.DecimalField(max_digits=10, decimal_places=2)
#     quantity = models.PositiveIntegerField()
#     block_quantity = models.IntegerField(default=0, blank=True, null=True)
#     available_quentity= models.IntegerField(default=1, blank=True, null=True)
#     created = models.DateTimeField(auto_now_add=True)
#     available = models.BooleanField(default=True)    
#     updated = models.DateTimeField(auto_now=True)    
#     Material_Type = models.CharField(blank = False ,null = False, max_length=40) #
#     Model_Number = models.CharField(blank = True ,null = True, max_length=40) #optional
#     ASIN = models.CharField(blank = True ,null = True, max_length=20) #optional

#     class Meta: 
#         ordering = ('-created',)
#         index_together = (('id', 'slug'),)
    
#     def __str__(self, **kwargs):
#         return self.name
    
#     def __str__(self):
#         return self.Product_SKU

#     # def get_absolute_url(self):
#     #     return reverse('shop:product_detail', args=[self.id, self.slug])

#     def get_absolute_url(self):
#         return reverse('shop:product_detail', args=[self.id, self.slug])

class CompanyName(models.Model):
    companyname_id = models.AutoField(primary_key=True)
    companyname = models.CharField(max_length=250, unique=True )
    
    

    def __str__(self):
        return self.companyname


class Company(models.Model): 
    Product_SKU = models.ForeignKey(Variant, related_name='prd_sku', on_delete=models.CASCADE)
    company_sku =  models.CharField(max_length=255, unique=True)
    company_name=models.ForeignKey(CompanyName, related_name='company_name', on_delete=models.CASCADE)
    # height = models.IntegerField(max_length=20)
    # width = models.IntegerField(max_length=20)
    # Company_Unit_Price= models.CharField(max_length=255)
    # Company_Retail_Price = models.CharField(max_length=255)
    # UPC/GTIN = models.IntegerField(max_length=20
    
    
    def __str__(self):
        return str(self.company_name)

    # def __str__(self):
    #    return self.company_name

class Manufacturer(models.Model):

    manufacturer_sku=models.CharField(max_length=250)
    manufacturer_name=models.CharField(max_length=250)
    manufacturer_product_Quantity =models.IntegerField(default=0)
    # Product_SKU = models.ForeignKey(Product, related_name='Manu_prd_sku')

    # def __str__(self):
    #     return (self.manufacturer_sku)

    


# def check_inventery(sender, **kwargs):#RECIVER
#     # if kwargs['created']:
#         #create_inventory= Order.objects.create(user=kwargs['instance'])
#     #create_inventory= Order.objects.create(user=kwargs['instance'])
#     quantity= Product.objects.all()
#     print quantity
#     print "message is recived"

shop/forms.py
from django import forms
from django.forms import MultiWidget
from .models import *

#FOR DISPLAYING DETAILS
class SimpleForm(forms.ModelForm):

    class Meta:
        model = Variant
        fields = ["variant_sku","variant_image" ,"title", "inventory_item_quantity"]




# class CreateForm(forms.ModelForm):

#     class Meta:
#         model = Product
#         fields = ["Product_SKU", "category", "image", "name", "quantity", "price", "bulletpoints", "description", "available_quentity", "Product_Dimensions", "Color", "ASIN", "Material_Type", ]
#         # fields = ["Product_SKU","image" ,"name","Product_id", "quantity","price","category"]

class CreateCategory(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        
class AddCompanySkuForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['Product_SKU', "company_sku", 'company_name']  
class AddCompanyForm (forms.ModelForm):
    class Meta:
        model = CompanyName
        fields = ['companyname']
    

shop/templates/shop/product/addcompany.html
{% extends "ordermanage/base.html" %} {% load staticfiles %} {% block title %}Add Company SKU{% endblock %} {% block body %}

<section>
    <div class="section-body">
        <div class="row">

            <div class="col s12">
                <div class="card">
                    <div class="card-head">
                        <header>Add Company SKU</header>
                        <div class="tools">
                            <!-- <a class="btn btn-icon-toggle btn-collapse">
                                <i class="fa fa-angle-down"></i>
                            </a> -->
                            <a href=" {% url 'shop:product_list'  %}">
                            <class="btn btn-icon-toggle btn-close">
                                <i class="md md-close"></i>
                            </a>
                        </div>
                    </div>

                    {% if messages %} {{ message }}
                    <ul class="messages">
                        <div id="modal1" class="modal">
                            <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat"><i class="material-icons">close</i></a> {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                                {% endfor %}
                        </div>
                    </ul>
                    {% endif %}

                    <div class="card-body">

                        <form class="col s12" action="#" method="POST">{% csrf_token %}

                            <div class="row">

                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_Product_SKU">Product SKU:</label> {{ form.Product_SKU}}

                                    </p>
                                </div>
                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_company_sku">Company sku:</label> {{ form.company_sku }}</p>
                                </div>

                            </div>

                            <div class="row">

                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_company_name">Company name:</label> {{ form.company_name}}

                                    </p>
                                </div>

                                <div class="input-field col s6">
                                    <div class=" input-field">
                                        <button class="btn cyan waves-effect waves-light" type="submit" value="SUBMIT">Submit
                                            <i class="material-icons right">send</i>

                                    </div>

                                </div>

                            </div>

                        </form>

                        <div class="row">
                            <div class="col s12">
                                <div class="input-field">

                                    <a href=" {% url 'shop:product_list'  %}">
                                        <button type="submit" class="btn cyan waves-effect waves-light right" style="margin-top:-125px"><i class=" close material-icons right white-text">close</i>Close</button>
                                    </a>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "ordermanage/base.html" %}
 {% load staticfiles %}
  {% block title %}Dashboard{% endblock %}

{% block body %}


<section id="content">
    
    <div class="container">
            
        
        <div id="card-stats">
            <div class="row">
                
                <div class="col s12 m6 l4">
                    <div class="card">
                        <div class="card-content red accent-2 white-text">
                            <p class="card-stats-title">
                                <a href="{% url 'shop:hundred' %}"><i class="material-icons">folder_open</i>Inventory More Than 100</p>
                            <h4 class="card-stats-number">{{ remain }}</h4></a>
                            <p class="card-stats-compare">
                                <i class="material-icons">keyboard_arrow_up</i>
                                <span class="red-text text-lighten-5">Product Status</span>
                            </p>
                        </div>
                        <div class="card-action red darken-1">
                            <div id="sales-compositebar" class="center-align"></div>
                        </div>
                    </div>
                </div>
                <div class="col s12 m6 l4">
                    <div class="card">
                        <div class="card-content teal accent-4 white-text">
                            <p class="card-stats-title">
                                    <a href="{% url 'shop:inventory_inrange' %}"><i class="material-icons">folder_open</i> Inventry range 20 to 100</p>
                            <h4 class="card-stats-number">{{ yellow }}</h4></a>
                            <p class="card-stats-compare">
                                <i class="material-icons">keyboard_arrow_up</i>
                                <span class="teal-text text-lighten-5">Product Status</span>
                            </p>
                        </div>
                        <div class="card-action teal darken-1">
                            <div id="profit-tristate" class="center-align"></div>
                        </div>
                    </div>
                </div>
                <div class="col s12 m6 l4">
                    <div class="card">
                        <div class="card-content deep-orange accent-2 white-text">
                                <a href="{% url 'shop:lesthantwenty' %}"><p class="card-stats-title">
                                <i class="material-icons">content_copy</i>Inventory less than 20</p>
                            <h4 class="card-stats-number">{{ red }}</h4></a>
                            <p class="card-stats-compare">
                                <i class="material-icons">keyboard_arrow_down</i>
                                <span class="deep-orange-text text-lighten-5">Product Status</span>
                            </p>
                        </div>
                        <div class="card-action  deep-orange darken-1">
                            <div id="invoice-line" class="center-align"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


      <section class="table" style="padding-left:0px !important; ">
               <div class="row">
                <div class="col m12 s12 ">
                  <div class="card  card-box">
                    <div class="card-head">
                     <header>Existing Inventory</header>
                  <div class="tools">
                      <a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
                      <a class="t-collapse btn-color fa fa-chevron-down" href="javascript:;"></a>
                      <a class="t-close btn-color fa fa-times" href="javascript:;"></a>
                  </div>
              </div>
                <div class="card-body">
                    <div class="table-wrap">
                         <div class="table-responsive">

                                <!--start msg-->
                                {% if messages %} {{ message }}
                                <ul class="messages">
                                    <div id="modal1" class="modal">
                                        <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat"><i class="material-icons">close</i></a> {% for message in messages %}
                                        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                                            {% endfor %}
                                    </div>
                                </ul>
                                {% endif %}
                                 <!--End msg-->

                          
                  <div class="table-responsive">

                    <form action="#" method="POST" enctype="multipart/form-data"> {% csrf_token %}

                              {% if "warehouse" in group1 or "superuser" in group1 %}
                                <a class="btn-floating btn-medium waves-effect waves-light red" href="{% url 'shop:create' %}"><i class="material-icons">add</i></a> 
                              {% endif %}

                      <table id="datatable2" class="table order-column hover">
                        <thead>
                      <tr>

                  {% comment %} <th><input type="checkbox" id="checkAll"></th> {% endcomment %}

                  <th><input type="checkbox" id="checkAll" ></th>

            <th>varient_SKU</th> 
            <th>Image</th>
            <th>Product Name</th>
            <th>variant Name</th>
            <th>Created Date</th>
            <th>Updated Date</th>
            <th>available_quantity</th>
            {% if "warehouse" in group1 or "superuser" in group1 %}
            <th>Button</th>
            {% endif %}
           

          </tr>
        </thead>


          <tbody> 
            {% for product in products %}
            <tr>
            <td><input type="checkbox" name="selectCheckbox"></td> 


              <td><a href="{{ product.get_absolute_url }}">{{ product.variant_sku }}</a><br></td>
              <td><a href="{{ product.get_absolute_url }}">
              <img src="{% if product.variant_image %}{{ product.variant_image.url }}{% else %}{% static "shop/img/no_image.png"%}{% endif %}" style="width: 150px;height: 80px;"></a></td>
              <td><a href="{{ product.get_absolute_url }}" style="    line-height:20px; font-size: 14px; color: #0e65a0;">{{ product.product_id.title }}</a></td>
              <td style=" font-size: 14px;">{{ product.title }}</td>
              <td style="font-size: 13px; padding-left: 0px;">{{ product.created }}</td>
              <td style=" font-size: 13px;">{{ product.updated }}</td>
              <td style="font-size: 14px;padding-left: 40px;">{{  product.inventory_item_quantity }}</td>

              {% if "warehouse" in group1 or "superuser" in group1 %}
              <td><a href="{% url "shop:edit" id=product.variant_id %}" class="btn ink-reaction btn-floating-action btn-warning"><i class="md md-edit"></i></a></td>
              {% endif %}
            </tr>

          
          {% endfor %}
        </tbody> 
        </table>
      </form>
    </div>
    </div>
    </div>
    </div>
  
</section>



  {% endblock %}

shop/templates/shop/product/list1.html
{% extends "ordermanage/base.html" %}
 {% load staticfiles %}
  {% block title %}Dashboard{% endblock %}

{% block body %}


<section id="content">
    
    <div class="container">
            
        
        <div id="card-stats">
            <div class="row">
                
                <div class="col s12 m6 l4">
                    <div class="card">
                        <div class="card-content red accent-2 white-text">
                            <p class="card-stats-title">
                                <a href="{% url 'shop:hundred' %}"><i class="material-icons">folder_open</i>Inventory More Than 100</p>
                            <h4 class="card-stats-number">{{ remain }}</h4></a>
                            <p class="card-stats-compare">
                                <i class="material-icons">keyboard_arrow_up</i>
                                <span class="red-text text-lighten-5">Product Status</span>
                            </p>
                        </div>
                        <div class="card-action red darken-1">
                            <div id="sales-compositebar" class="center-align"></div>
                        </div>
                    </div>
                </div>
                <div class="col s12 m6 l4">
                    <div class="card">
                        <div class="card-content teal accent-4 white-text">
                            <p class="card-stats-title">
                                    <a href="{% url 'shop:inventory_inrange' %}"><i class="material-icons">folder_open</i> Inventry range 20 to 100</p>
                            <h4 class="card-stats-number">{{ yellow }}</h4></a>
                            <p class="card-stats-compare">
                                <i class="material-icons">keyboard_arrow_up</i>
                                <span class="teal-text text-lighten-5">Product Status</span>
                            </p>
                        </div>
                        <div class="card-action teal darken-1">
                            <div id="profit-tristate" class="center-align"></div>
                        </div>
                    </div>
                </div>
                <div class="col s12 m6 l4">
                    <div class="card">
                        <div class="card-content deep-orange accent-2 white-text">
                                <a href="{% url 'shop:lesthantwenty' %}"><p class="card-stats-title">
                                <i class="material-icons">content_copy</i>Inventory less than 20</p>
                            <h4 class="card-stats-number">{{ red }}</h4></a>
                            <p class="card-stats-compare">
                                <i class="material-icons">keyboard_arrow_down</i>
                                <span class="deep-orange-text text-lighten-5">Product Status</span>
                            </p>
                        </div>
                        <div class="card-action  deep-orange darken-1">
                            <div id="invoice-line" class="center-align"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


      <section class="table" style="padding-left:0px !important; ">
               <div class="row">
                <div class="col m12 s12 ">
                  <div class="card  card-box">
                    <div class="card-head">
                     <header>Existing Inventory</header>
                  <div class="tools">
                      <a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
                      <a class="t-collapse btn-color fa fa-chevron-down" href="javascript:;"></a>
                      <a class="t-close btn-color fa fa-times" href="javascript:;"></a>
                  </div>
              </div>
                <div class="card-body">
                    <div class="table-wrap">
                         <div class="table-responsive">
                          {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}><p class="text-danger">{{ message }}</p></li>
                        {% endfor %}
                    </ul>
                  {% endif %}
                  <div class="table-responsive">

                    <form action="#" method="POST" enctype="multipart/form-data"> {% csrf_token %}
                                <a class="btn-floating btn-medium waves-effect waves-light red" href="{% url 'shop:create' %}"><i class="material-icons">add</i></a> 

                     
                      <table id="datatable2" class="table order-column hover">
                        <thead>
                      <tr>

                  {% comment %} <th><input type="checkbox" id="checkAll"></th> {% endcomment %}

                  <th><input type="checkbox" id="checkAll" ></th>

            <th>Merchant_SKU</th> 
            <th>Image</th>
            <th>Product Name</th>
            <th>Product ID</th>
            <th>Created Date</th>
            <th>Updated Date</th>
            <th>Total Items</th>

            <th>Button</th>

          </tr>
        </thead>


          <tbody>
            {% for product in products %}
            <tr>
            <td><input type="checkbox" name="selectCheckbox"></td> 


              <td><a href="{{ product.get_absolute_url }}">{{ product.Product_SKU }}</a><br></td>
              <td><a href="{{ product.get_absolute_url }}">
              <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "shop/img/no_image.png"%}{% endif %}" style="width: 150px;height: 80px;"></a></td>
              <td><a href="{{ product.get_absolute_url }}" style="    line-height:20px; font-size: 14px; color: #0e65a0;">{{ product.name }}</a></td>
              <td style=" font-size: 14px;">{{ product.Product_id }}</td>
              <td style="font-size: 13px; padding-left: 0px;">{{ product.created }}</td>
              <td style=" font-size: 13px;">{{ product.updated }}</td>
              <td style="font-size: 14px;padding-left: 40px;">{{  product.available_quentity }}</td>
              <td><a href="{% url "shop:edit" id=product.id %}" class="btn ink-reaction btn-floating-action btn-warning"><i class="md md-edit"></i></a></td>
            </tr>

          
          {% endfor %}
        </tbody> 
        </table>
      </form>
    </div>
    </div>
    </div>
    </div>
  
</section>



  {% endblock %}