core/urls.py
from django.urls import path, include
from django.contrib import admin
import django.core.handlers.wsgi
from . import views 
from django.conf.urls.static import static
from django.conf import settings
from .forms import LoginForm, SignUpForm, AuthenticationForm, EmailAuthenticationForm
from django.contrib.auth import views as auth_views
from . import api
# from rest_framework_jwt.views import obtain_jwt_token
from rest_framework.authtoken.views import obtain_auth_token
urlpatterns = [
    
 
    path('admin/',admin.site.urls),
    # path('<str:hmac>/<str:locale>/<str:session>/<str:shop>/<str:timestamp>/',include('shop.urls'))
    path('',views.user_login, name='mvp'),
    path('ordermanage/',include('ordermanage.urls')),
    path('signup/',views.signup,name='signup'),
    path('logout/',django.contrib.auth.views.LogoutView.as_view(),name='logout'),
    path('shop/',include('shop.urls')),
    path('shopify_app/',include('shopify_admin.urls')),
    
    path('mf_store/',include('mfStore.urls')),



    #PASSWORD VIEWS - AUTH BASED
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('auth/',include('rest_framework_social_oauth2.urls')),#heroku comment

#####################################react app###############################################    
    path('frontend/',include('frontend.urls')),
#############################################################################################
#############################################################intregting api with #############################    
    path('apitoken/', obtain_auth_token, name='api_token_auth'),
    path('api/',api.auth.as_view()),
    path('api/signup/',api.Signup.as_view()),
    path('api/product_list/',api.Product_list.as_view()),
    path('api/product_list/<str:rate>/',api.get_by_count.as_view()),
    path('api/shopify/',api.getshopify.as_view())
#########################################################################################
    
]


"""for Lodaing Static files in django """

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""End Of  Lodaing Static files in django """

mfStore/urls.py
from django.urls import path,include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    # url(r'^wh_order/$', views.warehouse_order, name="wh_order"),
    # url(r'^create_order/$', views.create_order, name="create_order"),
    # url(r'^(?P<id>\d+)/details/$', views.order_details, name="details"),
    # url(r'^(?P<id>\d+)/edit/$', views.OrderEdit, name="edit"),
    # url(r'^add_manufacturer/$', views.add_manufacturer, name="add_manufacturer"),
    # url(r'^map_manufacturer/$', views.map_manufacturer_sku, name="map_manufacturer"),
    # url(r'^test_all/$', views.linetblcreate,
    #     name="test_all"),
    # url(r'^mf_list/$', views.ManufacturerOrderlist, name="mf_list"),
    # url(r'^email/$', views.emailFunction, name="email"),
    # url(r'^(?P<id>\d+)/line_edit/$', views.lineItemEdit, name="line_edit"),
    # url(r'^(?P<id>\d+)/ship_details',
    #     views.shipPositionDetails, name="ship_details"),
    # url(r'^ship_position/$', views.shipPosition, name="ship_position"),
    # url(r'^(?P<id>\d+)/lineitem',
    #     views.lineitemDetails, name="lineitem"),
    # url(r'^(?P<id>\d+)/editlineitem',
    #     views.EditlineitemDetails, name="editlineitem"),
    # url(r'^ReadXmlData/$', views.ReadXmlData, name="ReadXmlData"),
    # url(r'^(?P<id>\d+)/shipdetails',
    #     views.EditlineitemDetination, name="shipdetails"),
    # url(r'^(?P<id>\d+)/pdf/$', views.generate_view,
    #     name="pdf"),
    # # url(r'^pdf/$', views.generate_view, name="pdf"),
    # url(r'^topdf/$', views.GeneratepackingSlip,
    #     name="topdf"),
    # url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     views.activate, name='activate'),
    path('create_order/', views.create_order, name="create_order"),
    path('<int:id>/details/', views.order_details, name="details"),
    path('<int:id>/edit/', views.OrderEdit, name="edit"),
    path('add_manufacturer/', views.add_manufacturer, name="add_manufacturer"),
    path('map_manufacturer/', views.map_manufacturer_sku, name="map_manufacturer"),
    path('test_all/', views.linetblcreate,
        name="test_all"),
    path('mf_list/', views.ManufacturerOrderlist, name="mf_list"),
    path('email/', views.emailFunction, name="email"),
    path('<int:id>/line_edit/', views.lineItemEdit, name="line_edit"),
    path('<int:id>/ship_details/',
        views.shipPositionDetails, name="ship_details"),
    path('ship_position/', views.shipPosition, name="ship_position"),
    path('<int:id>/lineitem/',views.lineitemDetails, name="lineitem"),
    path('<int:id>/editlineitem',views.EditlineitemDetails, name="editlineitem"),
    path('ReadXmlData/', views.ReadXmlData, name="ReadXmlData"),
    path('<int:id>/shipdetails/',
        views.EditlineitemDetination, name="shipdetails"),
    path('<int:id>/pdf/', views.generate_view,
        name="pdf"),
    path('topdf/', views.GeneratepackingSlip,
        name="topdf"),
    path('activate/<uidb64>/<token>/',views.activate,name='activate'),
    # path('sed/',views.sedmail)
]

mfStore/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from shop.models import *
import random
from django.core.validators import RegexValidator
import datetime

# Create your models here.

# >>>>>> for rendom number


def random_text():  # not in use
    text = 'WH_PO'
    val = random.randint(100, 1000)
    output = '{}-{}'.format(text, val)
    return output


OrderStatus = (('open', 'Open'),
               ('close', 'Close'),
               ('na', 'NA'))


Stepprogress = (
    ('1', 'Out-from-MFStore'),
    ("2", "Dispatch for warehouse"),
    ("3", "On The Ship"),
    ("4", "Reached Destination"),
    ("5", "Deliverd")

)

status = (
    ("Pending", "Pending"),
    ('Acknowledge', 'Acknowledge'),
    ("Completed", "Completed"),
)


"""==============================="""
""">>>>>Create Manufacturer Table """
"""==============================="""


class AddManufacturer(models.Model):
    # manufacturer_name = models.ForeignKey(
    #     User, on_delete=models.CASCADE, related_name='manufacturer_name')
    manufacturer_name = models.CharField(
        max_length=255, verbose_name='Manufacturer Name')
    # email = models.EmailField(max_length=70, blank=True)
    # password =  models.CharField(max_length =20, blank =true)
    manufacturer_loction = models.CharField(max_length=50, null=False)

    def __str__(self):
        return str(self.manufacturer_name)


"""======================================="""
""">>>>>Create Manufacturer Mapping Table """
"""======================================="""


class ManufacturerMapping(models.Model):
    Product_SKU = models.ForeignKey(Variant, related_name='Mf_Sku', on_delete=models.CASCADE)
    Manufacturer_SKU = models.CharField(max_length=255, unique=True)
    # company_name = models.ForeignKey(
    #     CompanyName, related_name='Manufacturer_Company')
    manufacturer = models.ForeignKey(
        AddManufacturer, related_name='Manufacturer_mapping', on_delete= models.CASCADE)

    def __str__(self):
        return str(self.Manufacturer_SKU)


"""====================================="""
""">>>>>Create Manufacturer Order Table """
"""====================================="""


class CreateManufacturerOrder(models.Model):
    invoice_no = models.CharField(
        default=random_text, max_length=20, unique=True, verbose_name="PO-Number")
    order_by = models.CharField(
        max_length=256, null=True)  # may be fk in future
    order_for = models.ForeignKey(
        Company, related_name='CompanyForOrder', on_delete=models.CASCADE)
    manufacturer_list = models.ForeignKey(
        AddManufacturer, related_name='ManufacturerNameList', on_delete=models.CASCADE)
    order_date = models.DateField(auto_now_add=True, blank=False, null=False)
    step_position = models.CharField(
        max_length=200, choices=Stepprogress, default="1")
    order_status = models.CharField(
        max_length=10, choices=OrderStatus, default="open")

    # brand = models.CharField(max_length=256, null=True)
    # sub_brand = models.CharField(max_length=256, null=True)
    # category = models.CharField(max_length=256, null=True)
    # type = models.CharField(max_length=256, null=True)
    # container = models.CharField(max_length=256, null=True)
    # multi_pack = models.CharField(max_length=256, null=True)
    # size = models.CharField(max_length=256, null=True)
    # order_to = models.CharField(max_length=256, null=True)  # choice field

    def __str__(self):
        return str(self.invoice_no)


"""===================================="""
""">>>>>Create Manufacturer Line Table """
"""===================================="""


class ManufactureLineTable(models.Model):
    manufacturer_table = models.ForeignKey(
        CreateManufacturerOrder, on_delete=models.CASCADE, related_name='linetable')
    item_sku = models.ForeignKey(
        ManufacturerMapping, on_delete=models.CASCADE, related_name='Manufacturar_linetable', null=True)
    item_name = models.CharField(max_length=255, null=True)
    dimention = models.CharField(
        max_length=255, null=True,)
    color = models.CharField(max_length=255, null=True)
    quantity = models.CharField(max_length=25, null=True)
    pack_size = models.IntegerField()
    delivery_date = models.DateTimeField(blank=True, null=True)
    Eta = models.DateTimeField(blank=True, null=True)
    step_position = models.CharField(
        max_length=200, choices=Stepprogress, default="1")
    mf_status = models.CharField(
        max_length=225, choices=status, default="Pending")
    warehouse_status = models.CharField(max_length=255, choices=status, default="Acknowledge")

    def __str__(self):
        return str(self.item_name)


"""===================================="""
""">>>>>>>>>> Create Address >>>>>>>>>>"""
"""===================================="""


class Address(models.Model):
    manufacturer_name = models.ForeignKey(
        CreateManufacturerOrder,
        on_delete=models.CASCADE,
        related_name="manufacturer_location")
    address = models.CharField(max_length=256, null=True)
    city = models.CharField(max_length=256, null=True)
    state = models.CharField(max_length=256, null=True)
    zip = models.CharField(max_length=15, null=True)
    contact_number = models.CharField(max_length=15, null=True)

    def __str__(self):
        return str(self.manufacturer_name)


"""===================================="""
""">>>>>>>>>>==== Remark ====>>>>>>>>>>"""
"""===================================="""


class remark(models.Model):
    wh_remark = models.ForeignKey(
        CreateManufacturerOrder, related_name="newupdate", verbose_name='UpdatedBy', on_delete=models.CASCADE)
    comment = models.CharField(max_length=500, verbose_name='Remark')
    date = models.DateTimeField(
        auto_now_add=True, auto_now=False)
    comment_by = models.ForeignKey(User, related_name='user_comment', on_delete=models.CASCADE)

    def __str__(self):
        return (self.comment)


"""===================================="""
""">>>>>==== Step ProgressBar====>>>>>>"""
"""===================================="""
Stepprogress = (
    ('1', 'Out-from-MFStore'),
    ("2", "Dispatch for warehouse"),
    ("3", "On The Ship"),
    ("4", "Reached Destination"),
    ("5", "Deliverd")
)


class WorkProgressBar(models.Model):
    # wh_address = models.ForeignKey(
    #     Address, on_delete=models.CASCADE,)
    lineitem = models.ForeignKey(
        ManufactureLineTable, on_delete=models.CASCADE)
    step_position = models.CharField(
        max_length=200, choices=Stepprogress, default="1")
    step_id = models.IntegerField(default=None,)
    step_description = models.TextField(max_length=255)
    location = models.CharField(max_length=255)
    date = models.DateField(auto_now_add=True, blank=True, null=True)
    Final_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return (self.step_position)

mfStore/forms.py
from django import forms
from django.forms import ModelForm, MultiWidget, ModelChoiceField
from .models import *
from shop.models import *
from django.contrib.admin.widgets import AdminDateWidget
from django.forms.fields import DateField
# from django.core import validators
from django.core.validators import RegexValidator


# class AddManufacturerForm(forms.ModelForm):
#     class Meta:
#         model = AddManufacturer
#         fields = ['manufacturer_name', 'manufacturer_loction']


class AddManufacturerForm(forms.ModelForm):
    password = forms.CharField(label='MF PassWord')
    email = forms.EmailField(label="Email")

    class Meta:
        model = AddManufacturer
        fields = ['manufacturer_name',
                  'manufacturer_loction',
                  ]

    def __init__(self, *args, **kwargs):
        super(AddManufacturerForm, self).__init__(*args, **kwargs)
        self.fields['manufacturer_name'].queryset = User.objects.filter(
            groups__name='manufacturer')


"""<<<<<<< === Manufacturer Maping Form === >>>>>>> """


class ManufacturerMappingForm(forms.ModelForm):
    class Meta:
        model = ManufacturerMapping
        fields = '__all__'


"""<<<<<<<<<<== create Manufacturer Order Form ==>>>>>>>>>>>>"""


class OrderRequestForm(forms.ModelForm):
    class Meta:
        model = CreateManufacturerOrder
        fields = [ "order_for", "manufacturer_list", "order_status"]


'''<<<<<<<<<<<<<<== Sku lineItem Form ==>>>>>>>>>>>>>>>>'''


class LineItemForm(forms.ModelForm):
    class Meta:
        model = ManufactureLineTable
        list_editable = ['quantity', 'delivery_date']
        fields = ['item_sku', 'item_name',
                  'dimention',
                  'color',
                  'quantity',
                  'delivery_date', ]
        widgets = {'manufacturer_table': forms.HiddenInput(),
                   'delivery_date': forms.DateInput(attrs={'type': 'date'}), }


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = '__all__'


class WorkProgressBarForm(forms.ModelForm):
    class Meta:
        model = WorkProgressBar
        fields = [
            "step_description",
            "location",
            "Final_date"]
        widgets = {'Final_date': forms.DateInput(attrs={'type': 'date'}), }

    # class EditOrderForm(forms.ModelForm):
    #     class Meta:
    #         model = CreateManufacturerOrder
    #         fields = [

    #         ]


class MfStatus(forms.ModelForm):
    class Meta:
        model = ManufactureLineTable
        fields = ['step_position']

mfStore/templates/mfStore/activate_account.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

mfStore/templates/mfStore/add_manufacturer.html
{% extends "ordermanage/base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block title %}Create order{% endblock %}
{% block body %}
{% if user.is_authenticated %}
<section>
    <div class="section-body">
        <div class="row">
            <div class="col s12">
                <div class="card">
                    <div class="card-head">
                        <header>Add Manufacturer</header>
                        <div class="tools">
                            <a class="btn btn-icon-toggle btn-collapse">
                                <i class="fa fa-angle-down"></i>
                            </a>
                            <a class="btn btn-icon-toggle btn-close" href="{% url 'mf_list' %}">
                                <i class="md md-close"></i>
                            </a>
                        </div>
                    </div>
                    {% if messages %}
                    <ul class="messages">
                        <div id="modal1" class="modal">
                            <a href="{% url 'add_manufacturer' %}"
                                class=" modal-action modal-close waves-effect waves-green btn-flat"><i
                                    class="material-icons">close</i></a>
                            {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                                {{ message }}
                            </li>
                            {% endfor %}
                        </div>
                    </ul>
                    {% endif %}

                    <!-- Form start From hear-->
                    <div class="card-body">
                        <form class="col s12" action="#" method="POST">{% csrf_token %}
                            <div class="row">
                                <div class="col s12 m4 l4">
                                    <div class="form-group">
                                        {{ form.as_p }}
                                    </div>
                                </div>
                                <div class="col s12 m4 l4">
                                    <div class="form-group">
                                        <input type="submit" name="Submit">
                                    </div>
                                </div>
                            </div>

                            <table id="data-table-simple" class="responsive-table display" cellspacing="0">
                                <thead>
                                    <tr>
                                        {% comment %}
                                        <hr />
                                        <th><input type="checkbox" id="checkAll" /></th>
                                        {% endcomment %}
                                        <th><input type="checkbox" id="checkAll" /></th>
                                        <th>Manufacturer Name:</th>
                                        <th>Manufacturer loction:</th>
                                        <th>Email</th>
                                        <!-- <th>Button</th> -->
                                    </tr>
                                </thead>

                                <tbody>
                                    {% for mf in query_results %}


                                    <!--PO Number-->
                                    <tr>
                                        <td>
                                            <input class="checkbox" type="checkbox" name="selectCheckbox" id=""
                                                value="" />
                                        </td>


                                        <td>
                                            <a href="">{{ mf.manufacturer_name }}</a>
                                        </td>

                                        <td>{{ mf.manufacturer_loction }}</td>

                                        <td>{% if mf.manufacturer_name.email %}{{ mf.manufacturer_name.email }}{% else %}------{% endif %}
                                        </td>
                                    </tr>

                                    {% endfor %}
                                </tbody>
                            </table>


                        </form>


                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endif %}{% endblock %}

mfStore/templates/mfStore/create.html
{% extends "ordermanage/base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}Create order{% endblock %}
{% block body %}
{% if user.is_authenticated %}
<section>
  <div class="section-body">
    <div class="row">
      <div class="col s12">
        <div class="card">
          <div class="card-head">
            <header>Create Manufacturer Order</header>
            <div class="tools">
              <a class="btn btn-icon-toggle btn-collapse">
                <i class="fa fa-angle-down"></i>
              </a>
              <a class="btn btn-icon-toggle btn-close" href="{% url 'mf_list' %}">
                <i class="md md-close"></i>
              </a>
            </div>
          </div>
          {% if messages %}
          <ul class="messages">
            <div id="modal1" class="modal">

              <a href="{% url 'create_order' %}" class=" modal-action modal-close waves-effect waves-green btn-flat">
                <i class="material-icons">close</i></a>
              {% for message in messages %}
              <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                {{ message }}
              </li>
              {% endfor %}
            </div>
          </ul>
          {% endif %}
          <!-- Form start From hear-->
          {% if "warehouse" in group1 %}

          <div class="card-body">
            <form class="col s12" action="#" method="POST">{% csrf_token %}
              <div class="row">
                <div class="col s12 m4 l4">
                  <div class="form-group">
                    <label class="bmd-label-floating">order_by</label>
                    <input type="text" value="{{request.user.username}}" readonly/>
                  </div>
                </div>
                {% for field in form %}
                <div class="col s12 m4 l4">
                  <div class="form-group">
                    <label for="{{ field.auto_id }}" class="bmd-label-floating">{{field.label_tag}}</label>
                    {{ field}}
                  </div>
                </div>
                {% endfor %}
                <!--Line Item Data -->
                {% for field in formItem %}
                <!-- <div class="col s12 m4 l4">
                    <div class="form-group">
                      {{field.label_tag}} {{ field}}
                    </div>
                  </div> -->
                {% endfor %}

                <!-- Address Fom data -->
                <div class="col s4">
                  <div class="form-group">
                    <!-- left unspecified, .bmd-form-group will be automatically added (inspect the code) -->
                    <label for="id_address" class="bmd-label-floating">Address</label>
                    <input type="text" class="form-control" id="id_address" name='address'>
                  </div>
                </div>

                <div class="col s4">
                  <div class="form-group">
                    <!-- left unspecified, .bmd-form-group will be automatically added (inspect the code) -->
                    <label for="id_city" class="bmd-label-floating">city:</label>
                    <input type="text" class="form-control" id="id_city" name='city'>
                  </div>
                </div>

                <div class="col s4">
                  <div class="form-group">
                    <!-- left unspecified, .bmd-form-group will be automatically added (inspect the code) -->
                    <label for="id_city" class="bmd-label-floating">State:</label>
                    <input type="text" class="form-control" id="id_state" name='state'>
                  </div>
                </div>

                <div class="col s4">
                  <div class="form-group">
                    <!-- left unspecified, .bmd-form-group will be automatically added (inspect the code) -->
                    <label for="id_zip" class="bmd-label-floating">zip:</label>
                    <input type="text" class="form-control" id="id_zip" name='zip'>
                  </div>
                </div>

                <div class="col s4">
                  <div class="form-group">
                    <!-- left unspecified, .bmd-form-group will be automatically added (inspect the code) -->
                    <label for="id_contact_number" class="bmd-label-floating">Contact Number:</label>
                    <input type="text" class="form-control" id="id_contact_number" name='contact_number'>
                  </div>
                </div>
                <div class="col s12 m6 l4">
                  <div class="form-group">
                    <!-- left unspecified, .bmd-form-group will be automatically added (inspect the code) -->
                    <label for="id_remark" class="bmd-label-floating">Comment:</label>
                    <textarea class="col" style="width:100%;" type="text" class="form-control rounded-0" id="id_remark"
                      name='remark'></textarea>
                  </div>
                </div>
                <div class="col s12 m6 l12">
                  <div class="form-group">
                    <!-- left unspecified, .bmd-form-group will be automatically added (inspect the code) -->
                    <div id="Lineitem" class="card card-box">
                      <ul class="commentdetail">
                        <li>
                          <input type="button" name="add new" id="addLineItem" value="Add More">
                        </li>
                      </ul>
                    </div>
                  </div>

                </div>
                <div class="col s12 m8 l8">
                  <div class="form-group">
                    <input type="submit" name="submit" value="Submit" />
                  </div>
                </div>
              </div>
            </form>
          </div>
          {% else %}
          <div class="container">
            <div class=" col s4 l4 m4 offset-s2"></div>
            <div class=" col s4 l4 m4 offset-s2">
              <div class="row offset-s2">
                <img src="/static/ordermanage/img/non.png" style="width:100%; height: 70%;" />

              </div>
            </div>
            <div class=" col s4 l4 m4 offset-s2"></div>
          </div>
          {% endif %}

        </div>
      </div>
    </div>
</section>
{% endif %}{% endblock %}

mfStore/templates/mfStore/editwp.html
{% extends "ordermanage/base.html" %}{% load staticfiles %}{% block title %}
Dashboard {% endblock %}{% block body %}
<section>
    </div>
</section>
<section>
    <div class="container ">
        <div class="row ">

            <div class="col m12 s12" style="margin-top:29px;">

                <div class="card  card-box">
                    <div class="card-head">
                        <header>WareHouse Orders Details</header>
                        <div class="tools">
                            <a class="btn btn-icon-toggle btn-collapse">
                                <i class="fa fa-angle-down"></i>
                            </a>
                            <a class="btn btn-icon-toggle btn-close" href="{% url 'mf_list' %}">
                                <i class="md md-close"></i>
                            </a>
                        </div>
                    </div>
                    <div class="card-body ">
                        <div class="container about">
                            <div class="row">
                                <div class="col s12 m12 l12">
                                    <div class="row" style="padding-left:6%; padding-right:5%; padding-bottom:20px;">
                                        {% include 'mfstore/stepprogressbar.html' %}
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

mfStore/templates/mfStore/invoice.html
{% extends "ordermanage/base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}Create order{% endblock %}
{% block body %}
{% if user.is_authenticated %}



{{invoice_id}}



{% endif %}

{% endblock %}

mfStore/templates/mfStore/test.html
<form method="POST">{% csrf_token%}
    {{ form.as_p }}
    <input type="submit" name="Submit">
</form>

// '<div class="col s12" style="margin-top:10px; margin-bottom:10px;" id="item1"><select name="new_Sku1"
        style="margin-right:20px; display:block !important;" id="new_Sku1">
        <option class="new_Sku" name="new_Sku">Select SKU</option>{%for item in ManufactureLineTable %}<option
            data-incr_value="1" value="{{item.Manufacturer_SKU}}" name="new_Sku">{{ item.Manufacturer_SKU }}</option>
        {% endfor %}
    </select>' +
    // '<label class="bmd-label-floating">quantity</label><input type=text value="1" name="qty">' + '<label
        class="bmd-label-floating">Pack Size</label><input type=text value="" name="pack_size">' + '<label
        class="bmd-label-floating">Max Delivery Date</label><input type=date value="" name="calender">' + '<input
        type="button" value="delete" id="delete"></div> ');

mfStore/templates/mfStore/test1.html
<h1>hello</h1>

mfStore/templates/mfStore/testall.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,height=device-height,initial-scale=1">
    <title>untitled document</title>
    <style media="screen">
        .hide {
            display: none;
        }
    </style>
</head>

<body>
    <form id="myform" action="#">
        <select id="location" name="drop">
            <option value="">drop selection</option>
            <option value="loc1">Location 1</option>
            <option value="loc2">Location 2</option>
            <option value="loc3">Location 3</option>
            <option value="loc4">Location 4</option>
            <option value="loc5">Location 5</option>
            <option value="loc6">Location 6</option>
            <option value="loc7">Location 7</option>
        </select>
        <select id="second" name="term">
            <option value="">term selection</option>
            <option value="OPT1">Option 1</option>
            <option value="OPT2">Option 2</option>
            <option value="OPT3">Option 3</option>
            <option value="OPT4">Option 4</option>
        </select>
    </form>
    <script>
        (function () {
            'use strict';
            /* jshint browser: true */
            var d = document;
            var mf = d.getElementById('myform');
            var se = d.getElementById('second');
            var lo = d.getElementById('location');
            var temp;
            mf.reset();
            se.className = 'hide';
            lo.onchange = function () {
                if (this.value === 'loc5') {
                    se.className = se.className.replace('hide', '');
                }
                else {
                    temp = this.value;
                    se.className = 'hide';
                    mf.reset();
                    lo.value = temp;
                }
            };
        }());
    </script>
</body>

</html>